# Generated by Django 3.1.7 on 2021-03-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_name', models.CharField(max_length=200)),
                ('rest_offer', models.CharField(max_length=200)),
                ('rating', models.CharField(max_length=10)),
                ('source', models.URLField()),
                ('date', models.DateField()),
                ('active', models.BooleanField()),
                ('expiration', models.DateField(null=True)),
            ],
        ),
    ]
