# Generated by Django 3.1.7 on 2021-03-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_auto_20210317_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
