# Generated by Django 3.1.7 on 2021-03-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_restarantinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='restarantinfo',
            name='rest_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
