# Generated by Django 3.1.7 on 2021-03-19 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0006_restarantinfo_rest_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restarantinfo',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='foods.offer'),
        ),
    ]
