# Generated by Django 3.1.7 on 2021-03-22 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0008_auto_20210319_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restarantinfo',
            name='rest_name',
            field=models.CharField(default='foodproject\x0coods\\placehold_stock.jpg', max_length=200),
        ),
    ]
